### ISSUE TITLE
Week 02

### ISSUE THREAD

**Issue by kjjee99** [escape-study/algorithm#3]
|DP|그래프 or 백트래킹|빡구현|특수유형|
|:-:|:-:|:-:|:-:|
|BOJ9251 LCS|BOJ6087 레이저|BOJ11559 puyo puyo|BOJ2470 두 용액|

**Comment by lsh9672** [comment]
DP : BOJ9251 LCS

**Comment by leemin-jae** [comment]
<table>
  <thead>
    <tr>
      <th>사이트</th>
      <th>번호</th>
      <th>이름</th>
      <th>난이도</th>
      <th>유형</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>BOJ</td>
      <td>2157</td>
      <td>여행</td>
      <td>골드4</td>
      <td>DP</td>
    </tr>
    <tr>
      <td>BOJ</td>
      <td>2141</td>
      <td>우체국</td>
      <td>골드4</td>
      <td>그리디</td>
    </tr>
    <tr>
      <td>BOJ</td>
      <td>2179</td>
      <td>비슷한 단어</td>
      <td>골드4</td>
      <td>문자열</td>
    </tr>
  </tbody>
</table>

**Comment by coldexpression** [comment]
DP, 백트랙킹 : BOJ1520 내리막 길

**Comment by lsh9672** [comment]
| |DP|그래프 or 백트래킹|빡구현|특수유형|
|:-:|:-:|:-:|:-:|:-:|
|BOJ9251 LCS|BOJ6087 레이저|BOJ11559 puyo puyo|BOJ2470 두 용액|

**Comment by sunmingLee** [comment]
DP | 그래프 or 백트래킹 | 빡구현 | 특수유형
-- | -- | -- | --
BOJ14567 선수과목 | BOJ16987 계란으로 계란치기 | BOJ21610 마법사 상어와 비바라 | BOJ13164 행복유치원

**Comment by kjjee99** [comment]
DP | 그래프 or 백트래킹 | 빡구현 | 특수유형
-- | -- | -- | --
BOJ2293 동전1 | BOJ17471 게리맨더링 | BOJ7682 틱택토 | BOJ15683 감시
